### ISSUE TITLE
X1-AV-61 Update GPIO pins in sensor classses

### ISSUE THREAD

**Issue by klemie** [UVicRocketry/Xenia1-Flight-Computer#117]
# Description
 <Describe what the feature or bug that need to be resolved>
 <Description of the big component that encompasses the issue working on>
 <Depencies, ex. libraries, sensors, hardware, small parts of code youhave to work on>
 <ow to do the things>

We need to set up all the pins that sensors are connected to in their sensor classes. Go to the wiring diagram on Alex's branch and follow the labels to the pi. Use CONSTANTS for the pins at the top of the files.

# Acceptance Criteria
 <Write specifically what is need for this issue to be completed>

- [ ] bme.py, lsm.py, adx.py, hx711s.py are updated with GPIO pins initialized 
- [ ] GPIO is sourced from Alexs wiring diagram 

# Dev Notes
[for assignee]<write down your thought process when developing this issue>

# Linked issues
 <If there are any related issues>

<Add to milestone>

**Comment by krislemie** [comment]
Sensors do this automatically. Might have to fix something with bus addressing
