### ISSUE TITLE
X1-AV-5 Fix Holes on Avionics Bay Assembly

### ISSUE THREAD

**Issue by klemie** [UVicRocketry/Xenia1-flight-Computer#17]
Update the locations of the holes on the avionics bay assembly to accommodate current sensors.

**Comment by jjderooy** [comment]
This is complete aside from the mounting for the camera which hasn't been chosen yet.

**Comment by jjderooy** [comment]
[Camera](https://www.aliexpress.com/item/1005001597402383.html?spm=a2g0o.productlist.0.0.70c03a391nkvqJ&algo_pvid=eaef896b-c060-4c3a-a719-652d853f8966&algo_exp_id=eaef896b-c060-4c3a-a719-652d853f8966-6&pdp_ext_f=%7B%22sku_id%22%3A%2212000016727750468%22%7D&pdp_pi=-1%3B12.01%3B-1%3B-1%40salePrice%3BCAD%3Bsearch-mainSearch) is now chosen and avionics bay holes are corrected.
