### ISSUE TITLE
X1-AV-12 HX711 reading

### ISSUE THREAD

**Issue by klemie** [UVicRocketry/Xenia1-flight-Computer#23]
Find the data sheet of the HX711 in this [](https://docs.google.com/document/d/1gTJJ3SIZ1-oAkT5Fk1SbSard9b0-FxJ6s4E3crWBEo4/edit) and see if there are any combatiable python libraries if not figure out how we would read the data.

**Comment by klemie** [comment]
Feb 16th update: Charlie hasn't been able to get anything done yet. Needs data sheet to look at driver info

**Comment by jjderooy** [comment]
This is the datasheet. It includes a C driver that could be rewritten in python if needed. [https://www.digikey.com/htmldatasheets/production/1836471/0/0/1/hx711.html](url)

**Comment by klemie** [comment]
- Meet up with @TechGal tomorrow at 4pm

**Comment by klemie** [comment]
https://github.com/UVicRocketry/Xenia1-flight-Computer/issues/27#issuecomment-1054649776

**Comment by klemie** [comment]
[multi HX711 Arduino](https://github.com/shmulike/HX711-multi)

**Comment by klemie** [comment]
mostly the framework is done. Having Troubles changing types. Just let python choose.

Having a hard time reading reading hex from the sensor.

**Comment by klemie** [comment]
@PokeyOne will help figure out c conversion

**Comment by jjderooy** [comment]
Finished in #56.
