### ISSUE TITLE
X1-AV-13 Make wiring diagram for whole system

### ISSUE THREAD

**Issue by krislemie** [UVicRocketry/Xenia1-Flight-Computer#25]
**Description**
- Create a writing diagram for the flight computer based off of previous diagrams

Previous Diagram: [diagram](https://app.diagrams.net/#G16KAys3ZIa_PrymFaww2CI59HlfeUq78S)
- Note this diagram is very out of date

**Acceptance Criteria**
- Updated Diagram KiCAD schematic uploaded to Xenia1-flight-computer 

**Dev Note**
[Write why you decided to do specific wiring arrangement in Pull Request]

**Comment by klemie** [comment]
Look at this diagram to see all the components https://drive.google.com/drive/u/0/folders/1lUKZYj5jFLF3oOM159mu564QdC9ljHMy

**Comment by klemie** [comment]
Alex is making a diagram in KiCAD

**Comment by TechGal** [comment]
![WIN_20220224_17_59_03_Scan](https://user-images.githubusercontent.com/14950228/156480391-c61cb4e6-6d61-4968-80e0-589b1f5fa77f.jpg)

**Comment by TechGal** [comment]
Next steps: put into kicad. and figure out where other sensors go

**Comment by klemie** [comment]
Finished 4 sensors in kicad

**Comment by krislemie** [comment]
review:
- change Wires to labels
- Harnesses

**Comment by TechGal** [comment]
Due by april 1st:

- [ ] Black box - USB connection (two pins Maybe DX and RX)
- [ ] ADC - addafruit 12bit analog to digtail converter (maybe 2 pins)
- [ ] Encoder - @TechGal

**Comment by TechGal** [comment]
This last iteration looks really good! Having all the wires run where they will run on the rocket will be very helpful for wiring. If you could label each wire with it's use or protocol, that would be even more helpful. Also, dividing the page using a double line or something so it's very clear where the wiring diagram is and where the full schematic is. It would be really nice if you could edit the RPi schematic object and add the camera port at the bottom, to remove the ambiguity of having that port as it's own separate thing. You can also label the Raven4s with APO -> Drogue, and Main -> Main. These are on the recovery bulkhead, so off to the right of the rest of the schematic (if we look at this as the rocket lying sideways).

Good work, thanks for taking this on.
