### ISSUE TITLE
X1-AV-16 Get data from Rpi camera 

### ISSUE THREAD

**Issue by klemie** [UVicRocketry/Xenia1-Flight-Computer#28]
**Description**
- The camera we will be using is a raspberry Pi camera look up its data sheet and see if it has a python library. 
- Decide weather to save the video in rocketData.py, in a separate file. 
- Make sure that it won't slow down our data transfer. If it does decouple it from 

**Acceptance Criteria**
- Video is either saved to a video file (That can be sent to black box) or configured in the code and ready to be saved and able to be directly sent to backbox
- See how you would save the camera data to the py and if how python would send it

**Dev Notes**
[for assignee in PR]<write down your thought process when developing this issue>

**Linked issues**
 <If there are any related issues>
Blocked by #33 use this info from this issue to code this issue

**Comment by TechGal** [comment]
Will be started later this week.

**Comment by MaiaPys** [comment]
Basic video capture script was written but not yet tested due to connectivity issues. Will be tested as soon as possible.

**Comment by TechGal** [comment]
@MaiaPys can you please send what you've been working on for the camera? We're hoping to bring together all the updates. Thanks!
