### ISSUE TITLE
X1-AV-18 Get[value] Airbrakes Stepper Potentiometer/Encoder

### ISSUE THREAD

**Issue by klemie** [UVicRocketry/Xenia1-Flight-Computer#30]
**Description**
- Get the potentiometer values from the airbrakes and store in rocketData object

**Acceptance Criteria**
- self._data is updated in rocketData.py with the new encoder value (make sure to test this with print statements show screenshots in PR)

**Dev Notes**
[for assignee in PR]<write down your thought process when developing this issue>

**Comment by jjderooy** [comment]
The device is just a potentiometer. As you spin it the ADC it is connected to will send a reading of 0-1023 (most likely) to the flight computer GPIO pins. It's just like the VEX potentiometers we used in engr120 if you remember those.

**Comment by jjderooy** [comment]
Hopefully mostly fixed in #53 . This at least lays the groundwork for it, though main will still need to actually put the data in rocketData from my understanding. None of the other data have integration with main yet so hopefully this is sufficient?
