### ISSUE TITLE
X1-AV---

### ISSUE THREAD

**Issue by TechGal** [UVicRocketry/Xenia1-flight-Computer#32]
Design a camera mount to hold a camera against the fuselage of the rocket, without requiring internal access to insert.

**Comment by jjderooy** [comment]
I'm not sure how you are organizing things but since this is a mech project rather than software would it make more sense for this to go on openproject?

**Comment by MorganStuyt** [comment]
@jjderooy & @TechGal Yes, this task is created in openproject.

**Comment by jjderooy** [comment]
Closing this with recommendation from Kris
