### ISSUE TITLE
X1-AV-21 PID Algorithm

### ISSUE THREAD

**Issue by klemie** [UVicRocketry/Xenia1-flight-Computer#34]
**Description**
- Create a PID controller to set the kalman output to the set output of the stepper position to
- This is the Kalman filter @TechGal dont think this issue is necessary 
(This might be over complicating it @TechGal )

**Acceptance Criteria**
 <Write specifically what is need for this issue to be completed>
- output of PID give a result in an exceptionable range

**Dev Notes**
[for assignee]<write down your thought process when developing this issue>

**Linked issues**
 <If there are any related issues>

**Comment by jjderooy** [comment]
I wouldn't bother with a PID controller for the stepper. The flaps don't need to deploy super fast and don't have much inertia either. The nice thing with steppers is that there is no overshoot. I'll close this in a bit unless there was a specific reason you (@klemie/@TechGal) wanted PID that I've missed.
