### ISSUE TITLE
X1-AV-31 Convert Sub-Orbit from Matlab to Python

### ISSUE THREAD

**Issue by ebert-c** [UVicRocketry/Xenia1-Flight-Computer#49]
**Description**
Sub-Orbit is a matlab program that will allow us to estimate our trajectory in real time.
We will be varying our drag utilizing the airbrakes to hit our target altitude.

We need to convert the Matlab program into Python and integrate it into the flight computer.
It will need to acquire sensor data and use that data to solve for the needed drag coefficient to achieve target altitude.

**Acceptance Criteria**
The Sub-Orbit program is converted to Python from Matlab and is able to receive sensor data from flight computer and output a drag coefficient that is needed to hit target altitude.

**Dev Notes**
[for assignee]<write down your thought process when developing this issue>

**Linked issues**
 <If there are any related issues>

<Add to milestone>

**Comment by PokeyOne** [comment]
https://github.com/UVicRocketry/Suborbit-Prediction-Script

**Comment by PokeyOne** [comment]
Currently there are three main components of this that need to be done: The atmosphere function, the power phase, and the coast phase.

Currently the atmosphere component is done, the power phase is almost done, and should be done tonight. The coast phase will be very similar to the power phase so this is getting very close to the matlab script.

**Comment by PokeyOne** [comment]
Next steps after this is done:
- Test on pi
- Is it fast enough?
- How are we integrating it with the rest?

**Comment by PokeyOne** [comment]
Quick update on this for May 18 2022.

I think this is probably closable?

This issue seems to be mostly the conversion of the script.

The script is fully converted over at <https://github.com/UVicRocketry/Suborbit-Prediction-Script> , and most of the stuff left to complete is optimization and evaluation.
