### ISSUE TITLE
X1-AV-32: Control Stepper Motors Based on Needed Drag Coefficient

### ISSUE THREAD

**Issue by ebert-c** [UVicRocketry/Xenia1-Flight-Computer#50]
**Description**
Given a needed drag coefficient, open the flaps controlled by the stepper motor to the position needed to achieve said drag.
A converter between drag coefficient and stepper motor position will be provided by Flight Dynamics.

**Acceptance Criteria**
When given a drag coefficient input, the system can cause the stepper motor to open the flaps to the position that provides that drag coefficient.

**Dev Notes**
[for assignee]<write down your thought process when developing this issue>

**Linked issues**
 <If there are any related issues>

<Add to milestone>

**Comment by TechGal** [comment]
Follow up with claire.

**Comment by TechGal** [comment]
Need updated drag coefficient list from claire.
