### ISSUE TITLE
X1-AV-33 Refactor HX711 driver for testing

### ISSUE THREAD

**Issue by klemie** [UVicRocketry/Xenia1-Flight-Computer#55]
**Description**
@cjsquires started #54 however this needs to be finished for testing. There were a lot of questions in that code so make sure to follow the reference Arduino driver word closely 
**Acceptance Criteria**
- Can read 12 HX711s

**Dev Notes**
[for assignee]<write down your thought process when developing this issue>

**Linked issues**
 <If there are any related issues>

<Add to milestone>

**Comment by jjderooy** [comment]
Nothing really needs to be refactored with the driver in #56. It does need to be tested with 12 HX711s on the PCB to be fully sure it works, but I have done quite a bit of testing with breakout boards and it does work fine with 2. I'll close this unless there were other things specifically you wanted to test.
